plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.arashyn.carbon'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.arashyn.carbon'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        release {
            def storeFilePath = System.getenv('CARBON_KEYSTORE_FILE')
            if (storeFilePath) {
                storeFile file(storeFilePath)
                storePassword System.getenv('CARBON_KEYSTORE_PASSWORD')
                keyAlias System.getenv('CARBON_KEY_ALIAS')
                keyPassword System.getenv('CARBON_KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (System.getenv('CARBON_KEYSTORE_FILE')) signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.6.2'
}
